### ISSUE TITLE
백그라운드로 실행했을때 출력 문제

### ISSUE THREAD

**Issue by richard0326** [youtube-jocoding/pyupbit-autotrade#8]
백그라운드로 실행했을때 output.log 파일에 아무것도 나오지 않네요...

```
$ nohup python3 bitcoinAutoTrade.py > output.log &
[1] 12607
$ nohup: ignoring input and redirecting stderr to stdout

$ vim output.log
```

이렇게 하면 빈화면입니다.

$ nohup python3 test.py > output.log &
이렇게 했을 때는 출력이 잘나오네요.

혹시 output buffer flush 문제일까요?? 그래도 출력이 아예 안되는 이유는 모르겠네요

**Comment by richard0326** [comment]
`nohup python3 bitcoinAutoTrade.py > ./output.log &`

이렇게 변경하니까 출력 잘 나오네요

**Comment by richard0326** [comment]
```
Traceback (most recent call last):
  File "/home/ubuntu/pyupbit-autotrade/bitcoinAutoTrade.py", line 49, in <module>
    current_price = get_current_price("KRW-BTC")
  File "/home/ubuntu/pyupbit-autotrade/bitcoinAutoTrade.py", line 33, in get_current_price
    return pyupbit.get_orderbook(ticker=ticker)["orderbook_units"][0]["ask_price"]
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyupbit/quotation_api.py", line 285, in get_orderbook
    orderbook, req_limit_info = _call_public_api(url, markets=ticker)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyupbit/request_api.py", line 64, in _call_public_api
    resp = _call_get(url, params=params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyupbit/errors.py", line 165, in wrapper
    resp = func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyupbit/request_api.py", line 42, in _call_get
    return requests.get(url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1017, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
```
